spring.application.name=notification-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

management.endpoints.web.exposure.exclude=health, prometheus
management.metrics.tags.application=${spring.application.name}

# 일단 유레카 설정
eureka.client.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false

server.port=${SERVER_PORT:8080}

# Account API 발행 이벤트 (실제 이름은 Account API 팀과 확인 필요)
rabbitmq.exchange.account-events=account.events
rabbitmq.queue.user-sync=notification.user-sync.queue
rabbitmq.routing-key.user-synced=user.synced
# Account API 강의실 구독 정보 (알림 설정 여부까지)
rabbitmq.queue.subscribe-sync=notification.sub-sync.queue
rabbitmq.routing-key.subscribe-sync=user.sub-synced

#telegram inbound
rabbitmq.exchange.telegram-events=telegram.events
rabbitmq.queue.telegram-inbound=notification.telegram-inbound.queue
rabbitmq.routing-key.telegram-inbound=telegram.inbound

# telegram
telegram.admin-bot.token=${TELEGRAM_ADMIN_BOT_TOKEN}
telegram.admin-bot.username=${TELEGRAM_ADMIN_BOT_USERNAME}
telegram.member-bot.token=${TELEGRAM_MEMBER_BOT_TOKEN}
telegram.member-bot.username=${TELEGRAM_MEMBER_BOT_USERNAME}
telegram.webhook.base-url=${TELEGRAM_WEBHOOK_BASE_URL}
