spring.datasource.url=jdbc:mysql://s4.java21.net:13306/${MYSQL_DATABASE:aiot03_team4}
spring.datasource.username=${MYSQL_USERNAME:aiot03_team4}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB:331}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

ollama.base-url=${OLLAMA_URL}
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

server.servlet.context-path=/notification

logging.level.root=INFO
logging.level.com.fourien.notification=INFO