spring.application.name=notification-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

management.endpoints.web.exposure.exclude=health, prometheus
management.metrics.tags.application=${spring.application.name}

server.port=${SERVER_PORT:8080}
